const appAsset = (fileName) => `/assets/app/${fileName}`;

export const assets = {
  arrow: appAsset("arrow.png"),
  google: appAsset("google.png"),
  avatar: appAsset("avatar.png"),
  prescription: appAsset("prescription.png"),
  medicalPrescription: appAsset("medical-prescription.png"),
  toplogo: appAsset("logo 2.png"),
  loginModel: appAsset("loginmodel.jpg"),
  ceo: appAsset("ceo.webp"),
  checkup: appAsset("checkup.png"),
  cure: appAsset("cure.png"),
  adminLogin: appAsset("adminLogin.jpg"),
  left: appAsset("left.png"),
  cart1: appAsset("cart1.jpg"),
  cart2: appAsset("cart2.jpg"),
  cart3: appAsset("cart3.jpg"),
  doctor: appAsset("doctor.png"),
  pharmacy: appAsset("medicine.png"),
  DoctorAvt1: appAsset("DoctorAvt1.png"),
  DoctorAvt2: appAsset("DoctorAvt2.png"),
  DoctorAvt3: appAsset("DoctorAvt3.png"),
  patientAvatar: appAsset("patientAvatar.png"),
  blog1: appAsset("blog1.jpg"),
  blog2: appAsset("blog2.jpg"),
  blog3: appAsset("blog3.jpg"),
  blog4: appAsset("blog4.jpg"),
  blog5: appAsset("blog1.jpg"),
  blog7: appAsset("blog7.jpg"),
  blog8: appAsset("blog8.jpg"),
  admin: appAsset("admin.png"),
  whyBlog: appAsset("why-us.jpg"),
  healthcare: appAsset("healthcare.png"),
  security: appAsset("security.png"),
  telemedicine: appAsset("telemedicine.png"),
  homeBG: appAsset("homeBG.png"),
  servicesMain: appAsset("services-main.jpg"),
  aboutBg: appAsset("about-bg.jpg"),
  patient: appAsset("patient.png"),
  HomeIcon: appAsset("homeIcon.png"),
  rightArrow: appAsset("rightArrow.png"),
  pharmacyAvt: appAsset("pharmacyAvt.png"),
  bookingAppointment: appAsset("bookingAppointment.png"),
  prescriptionImg: appAsset("prescriptionImg.png"),
  notFoundDoctor: appAsset("404_doctor.png"),
  abstractShapes: appAsset("abstract_shapes.png"),
  auth_patient_care: appAsset("auth_patient_care.jpg"),
  auth_doctor_telehealth: appAsset("auth_doctor_telehealth.jpg"),
  auth_admin_workspace: appAsset("auth_admin_workspace.jpg"),
  auth_bg_1: appAsset("auth_bg_1.jpg"),
};
